services:
  - type: web
    name: express-auth-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000 
      - key: MONGO_URI
        value: mongodb+srv://<sayan>:<Sayan123>@<cluster>.mongodb.net/<dbname>?retryWrites=true&w=majority  
