services:
  - type: web
    name: express-auth-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000   # Optional, Render injects PORT automatically too
